### ISSUE TITLE
Missing Bento4 applications

### ISSUE THREAD

**Issue by svensson00** [Eyevinn/docker-toolbelt#1]
I noticed that the Bento4 installation is missing a few applications (mp4hls, mp4dash and mp4dashclone). I tried to install Bento4 in a new "empty" Ubuntu container and got the same problem. If you however download the already built binaries you get all applications.

Using the eyevinn user when this was found.

**Comment by birme** [comment]
This is now solved in v3.3 and latest tag

```
docker run -it -v /Users/myuser:/mnt eyevinntechnology/toolbelt:latest /bin/bash
```

It was the Python scripts that I failed to install from the build
